settings:
  autoUpgrade: true

packages:
  copr-ostree:
    - "https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-43/solopasha-hyprland-fedora-43.repo"
    - "https://copr.fedorainfracloud.org/coprs/scottames/vicinae/repo/fedora-43/scottames-vicinae-fedora-43.repo"
    - "https://copr.fedorainfracloud.org/coprs/scottames/ghostty/repo/fedora-43/scottames-ghostty-fedora-43.repo"
  brew:
    - "soft-serve"
    - "gum"
    - "stikypiston/formulae/hocusfocus"
    - "zoxide"
    - "viu"
    - "feh"
    - "yt-dlp"
    - "vhs"
    - "glow"
    - "charmbracelet/tap/freeze"
    - "aerc"
    - "yazi"
    - "grex"
    - "jrnl"
    - "croc"
    - "sysbench"
    - "pkl"
    - "swift"
    - "pkl-lsp"
    - "gh"
    - "stikypiston/formulae/dotkeeper"
    - "tlrc"
    - "delta"
    - "lazygit"
    - "stan-breaks/ytsurf/ytsurf"
    - "stikypiston/formulae/dotkeeper-tui"
    - "luarocks"
    - "npm"
    - "ripgrep"
    - "timewarrior"
    - "helix"
    - "git-lfs"
    - "utftex"
    - "ncdu"
    - "stikypiston/formulae/chess-tui"
    - "stockfish"
    - "yarn"
    - "w3m"
    - "amfora"
    - "gleam"
    - "erlang"
    - "stikypiston/formulae/recall"
    - "zinit"
    - "bob"
    - "stikypiston/formulae/fastcards"
    - "asciinema"
    - "stikypiston/formulae/pricetag"
    - "fd"
    - "stikypiston/formulae/bobafm"
    - "dart-sdk"
    - "stikypiston/formulae/decree"
    - "superfile"
    - "starship"
    - "fastfetch"
    - "tmux"
    - "bat"
    - "eza"
    - "rustup"
  flatpak:
    - "org.prismlauncher.PrismLauncher"
    - "md.obsidian.Obsidian"
    - "org.gnome.World.Secrets"
    - "app.zen_browser.zen"
    - "org.kde.kdenlive"
    - "io.missioncenter.MissionCenter"
    - "cc.arduino.IDE2"
    - "it.mijorus.gearlever"
    - "org.libreoffice.LibreOffice"
    - "org.nickvision.tubeconverter"
    - "de.schmidhuberj.tubefeeder"
    - "de.haeckerfelix.Fragments"
    - "org.cockpit_project.CockpitClient"
    - "org.gnome.World.PikaBackup"
    - "com.github.iwalton3.jellyfin-media-player"
    - "org.videolan.VLC"
    - "com.unicornsonlsd.finamp"
    - "org.freedesktop.Platform.ffmpeg-full"
    - "org.freedesktop.Platform.VulkanLayer.MangoHud"
    - "com.github.tchx84.Flatseal"
    - "com.belmoussaoui.Authenticator"
    - "com.mardojai.ForgeSparks"
    - "com.modrinth.ModrinthApp"
    - "net.ankiweb.Anki"
    - "menu.kando.Kando"
    - "org.localsend.localsend_app"
    - "io.github.giantpinkrobots.varia"
    - "org.freedesktop.Platform.VulkanLayer.MangoHud//24.08"
    - "org.vinegarhq.Vinegar"
    - "org.vinegarhq.Sober"
    - "org.winehq.Wine"
  rpm-ostree:
    - "zsh"
    - "niri"
    - "waybar"
    - "swww"
    - "ghostty"
    - "fuzzel"
